### ISSUE TITLE
dmarc_es01_1   memory usage

### ISSUE THREAD

**Issue by redsector72** [evermight/elk-dmarc#1]
Hi @evermight,
I'm testing your nice work.
I've just noticed that the dmarc_es01_1  image takes almost 7gb of ram. There is any way/parameter to set to lower this to a minimum?
Thanks!

**Comment by johnlai2004** [comment]
> Hi @evermight, I'm testing your nice work. I've just noticed that the dmarc_es01_1 image takes almost 7gb of ram. There is any way/parameter to set to lower this to a minimum? Thanks!

Thanks for your message.  Unfortunately and to my knowledge, Elasticsearch does use up a lot of memory. IN my other tutorial traditional installation of elasticsearch, i mention that you should have at least 8GB of memory.  When I had less then that, elasticsearch can fail to start up.

**Comment by johnlai2004** [comment]
I have updated readme to mention need for 8GB memory and will now close this ticket.  Thank you veyr much for raising this point.
