### ISSUE TITLE
Error response from daemon: No such container: dmarc-parser-1

### ISSUE THREAD

**Issue by HichamAl** [evermight/elk-dmarc#3]

**Comment by HichamAl** [comment]
I made a pull request to fix this error.

**Comment by johnlai2004** [comment]
Thank you, i have updated the readme to expain that you should use the `docker ps -a` command to figure out your container names.  Different versions of operating system/docker/other configurations affect the names of your containers.  So when it doubt, `docker ps -a` will tell you your container names.


Read me has been updated. THank you for pointing thiis out. I'll close this ticket now
